"""Decisions you made about your folders, kept where they survive the index.

`index.db` is disposable. The README says so, `rebuild()` proves it, and several
tests exist only to keep it true — delete it and the whole journal comes back
from Markdown for free.

Everything came back except two things, and both were decisions somebody made by
hand: a folder name you typed, and a split you turned down. They lived in the
index and nowhere else, so the one operation the app advertises as costless
quietly discarded the only state in the system that could not be re-derived.
Deleting the index is not exotic — it is the documented fix for a corrupt cache
and there is a route for it.

The cause was that a folder has nowhere to record a fact about *itself*. Entries
carry their own frontmatter and everything else is rebuilt from that; a folder is
only implied by the labels its members happen to hold.

So this file is that place, and it lives in the journal folder rather than the
support directory for the same reason ``agent.md`` does: **the journal folder
holds what you authored.** A name you typed and a suggestion you declined are
both things you authored.

Keyed on the label, and that is not a shortcut. Theme ids are minted by
``_restore_structure`` when it meets a label it does not recognise, so ids are
regenerated by a rebuild from an empty index and cannot identify anything across
one. The label is the only durable name a folder has.
"""

from __future__ import annotations

import logging
from pathlib import Path

import frontmatter
from pydantic import BaseModel, Field

log = logging.getLogger(__name__)

PREAMBLE = """\
Folders Tilt keeps a note about.

`pinned` are folders you renamed. Tilt will not rename them back.

`declined` are splits you turned down — the folder Tilt thought had become two
subjects, and how many entries were in it when you said no. It asks again only
once a folder has grown by half as much again.

Both are here rather than in the database because a database is a cache and this
is not. Edit or delete anything; nothing here is load-bearing for your entries.
"""


class Declined(BaseModel):
    """A split proposal turned down, and how big the folder was at the time."""

    folder: str
    at: int = 0


class Decisions(BaseModel):
    pinned: list[str] = Field(default_factory=list)
    declined: list[Declined] = Field(default_factory=list)

    def is_pinned(self, label: str) -> bool:
        return any(p.casefold() == label.casefold() for p in self.pinned)

    def declined_at(self, label: str) -> int | None:
        for item in self.declined:
            if item.folder.casefold() == label.casefold():
                return item.at
        return None


class FolderStore:
    """Reads and writes ``folders.md`` in the journal folder.

    A missing or malformed file yields no decisions rather than an error. The
    failure to protect against is losing a folder name, and refusing to boot
    over mistyped YAML would be a worse version of the same problem.
    """

    def __init__(self, path: Path) -> None:
        self.path = path

    def load(self) -> Decisions:
        if not self.path.exists():
            return Decisions()
        try:
            post = frontmatter.load(self.path)
            return Decisions(
                pinned=[str(x) for x in post.metadata.get("pinned") or []],
                declined=[
                    Declined(folder=str(d.get("folder", "")), at=int(d.get("at", 0) or 0))
                    for d in (post.metadata.get("declined") or [])
                    if isinstance(d, dict) and d.get("folder")
                ],
            )
        except Exception:
            log.warning("could not read %s; carrying on with no folder decisions", self.path)
            return Decisions()

    def save(self, decisions: Decisions) -> Decisions:
        self.path.parent.mkdir(parents=True, exist_ok=True)
        post = frontmatter.Post(
            PREAMBLE,
            pinned=sorted(decisions.pinned, key=str.casefold),
            declined=[d.model_dump() for d in decisions.declined],
        )
        self.path.write_text(frontmatter.dumps(post), encoding="utf-8")
        return decisions

    # ------------------------------------------------------------- recording

    def pin(self, label: str) -> None:
        """Remember that this name is yours."""
        decisions = self.load()
        if decisions.is_pinned(label):
            return
        decisions.pinned.append(label)
        self.save(decisions)

    def rename(self, old: str, new: str) -> None:
        """Follow a pin through a rename, so it is not orphaned on the old name."""
        decisions = self.load()
        decisions.pinned = [p for p in decisions.pinned if p.casefold() != old.casefold()]
        if not decisions.is_pinned(new):
            decisions.pinned.append(new)
        # A declined split follows the folder too: it was about this subject,
        # not about what it was called that week.
        for item in decisions.declined:
            if item.folder.casefold() == old.casefold():
                item.folder = new
        self.save(decisions)

    def forget(self, label: str) -> None:
        """Drop every decision about a folder that no longer exists."""
        decisions = self.load()
        before = (len(decisions.pinned), len(decisions.declined))
        decisions.pinned = [p for p in decisions.pinned if p.casefold() != label.casefold()]
        decisions.declined = [
            d for d in decisions.declined if d.folder.casefold() != label.casefold()
        ]
        if (len(decisions.pinned), len(decisions.declined)) != before:
            self.save(decisions)

    def decline(self, label: str, *, members: int) -> None:
        """Remember that a split of this folder was turned down, and its size then."""
        decisions = self.load()
        for item in decisions.declined:
            if item.folder.casefold() == label.casefold():
                item.at = members
                break
        else:
            decisions.declined.append(Declined(folder=label, at=members))
        self.save(decisions)

    def accepted(self, label: str) -> None:
        """A split that happened settles the question; the refusal is spent."""
        decisions = self.load()
        keep = [d for d in decisions.declined if d.folder.casefold() != label.casefold()]
        if len(keep) != len(decisions.declined):
            decisions.declined = keep
            self.save(decisions)
